### ISSUE TITLE
Add map filters

### ISSUE THREAD

**Issue by a-chabin** [ekaterinburgdev/map#16]
Our designers (@kryaazh, @Omelekhin) have developed a nice accordion filter for all types of data on the map.

@hiba9201, @C-reshetka partially shows objects on the map from the backend
(PRs: https://github.com/ekaterinburgdev/map/pulls?q=is%3Apr+is%3Aclosed+author%3Ahiba9201)

## Tasks
- [x] Add accordion toggle controls
- [x] Add filters to map
   - [x] Design-code objects (#30)
   https://github.com/ekaterinburgdev/map/blob/main/common/data/designCode/designCode.ts
   - [x] DTP (#33)
   https://github.com/ekaterinburgdev/map/blob/main/common/data/dtp/dtp.ts
   - [x] OKN (#28)
   - [x] Lines: red, pink, blue (#31)
   https://github.com/ekaterinburgdev/map/blob/main/common/data/okn/okn.ts
   - [x] Houses age (#17)
   https://github.com/ekaterinburgdev/map/blob/main/common/data/houseAge/houseAge.ts
   - [x] Houses floors (#21)
   https://github.com/ekaterinburgdev/map/blob/main/common/data/houseFloor/houseFloor.ts

We can make accordion and filters in **separately** PR's.

## Design

https://www.figma.com/file/VpUQ8aZanmAIbwlSt5UTKH/%F0%9F%9A%B2-Ekaterinburg.design?node-id=3460%3A2199&t=R24W5OHRqtStQd9t-1

<a href="https://user-images.githubusercontent.com/22644149/231880122-5fd1caa2-2ea0-45ac-8be4-02d370e9d181.png"><img src="https://user-images.githubusercontent.com/22644149/231880122-5fd1caa2-2ea0-45ac-8be4-02d370e9d181.png" alt="" width="50%"></a>

## Links
**`<RangeHistorgram>` by @gcor**
https://ekbdev-ni8bz9874-ekbdev.vercel.app

https://github.com/ekaterinburgdev/map/tree/main/components/UI/RangeHistogram

**Commit with Range settings**
https://github.com/ekaterinburgdev/map/commit/dc82735aab01f36d0a643319365a6775abc298ad#diff-8bee326fb9b20affb6442d72dbed13219264c79dce704b1fae8ddb04b711e24cL65

**Data**
https://github.com/ekaterinburgdev/map/tree/main/common/data

**Draft PR - https://github.com/ekaterinburgdev/map/pull/14 (closed now)**
I started create draft PR for this control. It's preview only — you don't have to use this solution :)
https://ekbdev-map-feature-filters.vercel.app/

**Accordion A11y guide**
https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/

**Comment by a-chabin** [comment]
Done #30, #33, #28, #31, #17, #21
